package reactions;

public enum ReactionType {

    // CHEMICAL REACTIONS
    DOUBLE_DISPLACEMENT,
    NEUTRALISATION,
    ELECTROLYSIS,
    CRYSTALLISATION,
    DISSOLUTION,
    SYNTHESIS,
    REDUCTION,
    OXIDATION,
    REDOX,

    // PHASE CHANGES
    SUBLIMATION,
    EVAPORATION,
    CONDENSATION,
    FREEZING,
    DEPOSITION
}
